version: "3"
services:
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    container_name: otel
    networks:
      - otel
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
    ports:
      - 13133:13133
      - 14250:14250
      - 14268:14268
      - 4317:4317
      - 6060:6060
      - 8888:8888
      - 9080:9080
      - 9411:9411
      - 9943:9943
 

  instrumented-java-application:
    image: zappos-apm-docker-demo
    container_name: app
    networks:
      - otel 
    ports:
      - 8080:8080
networks:
  otel:
    # Use Bridge to simplify networking
    driver: bridge
